apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy

on: 
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  login:
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo "logging in..."
  
  verify:
    uses: p-gombola/shared/.cloudbees/workflows/verify.yaml@main