apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_dispatch: {}
  workflow_call:
    inputs:
      username:
        type: string
        description: The username to use for deploying
        required: false
        default: system
    secrets:
      deploy_pwd:
        description: The password to use for deploying
        required: true
jobs:
  scan:
    uses: p-gombola/shared/.cloudbees/workflows/scan.yaml
      
  prod:
    steps:
      - uses: docker://alpine:3.20
        id: get-token
        run: |
          if [ "${{secrets.deploy_pwd}}" != "" ]; then
            echo "authenticated!"
            echo "ZGVhZGJlZWYK" > token
          else
            echo "mising deploy_pwd secret"
            exit 1
          fi
      - uses: docker://alpine:3.20
        run: |
          echo "auth token: `cat token`"
          echo "${{inputs.username}} is deploying to prod..."

  staging:
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo "deploying staging..."
