apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy

on: 
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  authenticate:
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo "authenticated."
  
  scan:
    uses: p-gombola/shared/.cloudbees/workflows/scan.yaml@v1

  deploy:
    needs: [scan, authenticate]
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo "deploying..."