apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy

on: 
  workflow_dispatch: {}
  workflow_call:
    secrets:
      deploy_pwd:
        description: The password to use for deploying
        required: true

jobs:
  prod-auth:
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo ${{secrets.deploy_pwd}}
  
  scan:
    uses: p-gombola/shared/.cloudbees/workflows/scan.yaml@v1

  prod:
    needs: [scan, prod-auth]
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo "deploying prod..."
  
  staging:
    needs: [scan]
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo "deploying staging..."
