apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy

on: 
  workflow_dispatch: {}
  
  workflow_call: {}

jobs:
  deploy-shared:
    steps:
      - id: deploy-app
        uses: docker://alpine:3.21
        run: |
          echo ${{ secrets.env-secret }}


