apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy

on: 
  workflow_call: {}

jobs:
  deploy:
    outputs:
      result: ${{ steps.deploy-app.outputs.result }}
    steps:
      - id: deploy-app
        uses: docker://alpine:3.21
        run: echo "pass" >> $CLOUDBEES_OUTPUTS/result



