apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy

on: 
  workflow_call: 
    inputs:
      config-path:
        required: true
        type: string
        default: ./config
        description: Path to config files for app
    secrets:
      access-token:
        required: true
        description: The token to use for deploying
    outputs:
      deploy-result:
        value: ${{ jobs.deploy.outputs.result }}
        description: pass or fail

jobs:
  deploy:
    outputs:
      result: ${{ steps.deploy-app.outputs.result }}
    steps:
      - id: deploy-app
        uses: docker://alpine:3.21
        run: echo "pass" >> $CLOUDBEES_OUTPUTS/result



