apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:      
  staging:
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo "deploying staging..."
