apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy

on: 
  workflow_dispatch: {}
  
  workflow_call: 
    inputs:
      config-path:
        required: true
        type: string
        default: ./config
        description: Path to config files for app
    secrets:
      access-token:
        required: true
        description: The token to use for deployingd
    outputs:
      deploy-result:
        value: ${{ jobs.deploy.outputs.result }}
        description: simple value output

jobs:
  deploy:
    steps:
      - id: deploy-app
        uses: docker://alpine:3.21
        run: |
          echo -n "pass" > $CLOUDBEES_OUTPUTS/result
    outputs:
      result: ${{ steps.deploy-app.outputs.result }}


