apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy

on: 
  workflow_call:
    secrets:
      top_secret:
        required: true

jobs:
  inner-1:
    steps:
      - id: deploy-app
        uses: docker://alpine:3.21
        run: |
          [ "${{ secrets.top_secret }}" = "secretFromEnv" ]

  call-rw-2:
    uses: p-gombola/shared/.cloudbees/workflows/scan.yaml@env-secret-bug-2
    secrets:
      top_secret_2: ${{ secrets.top_secret }}


