apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: verify-deploy

on:
  workflow_call:
    secrets:
      top_secret_2:
        required: true

jobs:
  inner-2:
    steps:
      - name: test secret value
        uses: docker://alpine:3.21
        run: |
          [ "${{ secrets.top_secret_2 }}" = "secretFromEnv" ]