apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: verify-deploy

on:
  workflow_call: {}

jobs:
  image:
    steps:
      - uses: docker://alpine:3.20
        run: |
          echo "image scanned..."