apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: verify-deploy

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  image:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout
      - uses: docker://alpine:3.20
        run: |
          echo `pwd`
          echo `ls -a .cloudbees`